Repository Team-TJ-Media/KioskProject, pull requests merged in 2025-04, with the labels that each got.

#7 [feat] 클린아키텍처 구조 구현
  KioskProject/App/Sources/DIContainer/KioskDIContainer.swift
  KioskProject/App/Sources/SceneDelegate.swift
  KioskProject/Data/Sources/DTO/Empty.swift
  KioskProject/Data/Sources/Repository/KioskRepository.swift
  KioskProject/Data/Sources/Service/KioskService.swift
  KioskProject/Domain/Sources/Entity/Empty.swift
  KioskProject/Domain/Sources/Repository Interface/KioskRepositoryInterface.swift
  KioskProject/Domain/Sources/UseCase Interface/KioskUseCaseInterface.swift
  KioskProject/Domain/Sources/UseCase/KioskUseCase.swift
  KioskProject/Presentation/Sources/DIContainer Interface/KioskDIContainerInterface.swift
  KioskProject/Presentation/Sources/ViewController/MainViewController.swift
  KioskProject/Presentation/Sources/ViewModel/MainViewModel.swift
Labels: enhancement

#12 [Fix/#11] viewController init 오류 수정
  KioskProject/Presentation/Sources/ViewController/MainViewController.swift
Labels: bug

#16 [Feat/#8] 타이틀, 주문/취소 버튼 추가
  KioskProject.xcodeproj/project.pbxproj
  KioskProject/Presentation/Sources/Component/OrderButton.swift
  KioskProject/Presentation/Sources/Component/OrderButtonView.swift
  KioskProject/Presentation/Sources/Component/TitleView.swift
  KioskProject/Presentation/Sources/View/MainView.swift
  KioskProject/Presentation/Sources/ViewController/MainViewController.swift
Labels: enhancement

#22 [feat/#18] AlertType 정의 및 UIViewController showAlert 메서드 구현
  KioskProject/Presentation/Sources/View/AlertType.swift
  KioskProject/Presentation/Sources/View/Extension+UIViewController.swift
Labels: enhancement

#23 Feature/#6 binding
  KioskProject/Data/Sources/DTO/ProductDTO/ProductResponseDTO.swift
  KioskProject/Data/Sources/Utils/Extension+Double.swift
  KioskProject/Domain/Sources/Entity/Product/Product Type/ProductType.swift
  KioskProject/Domain/Sources/Entity/Product/Product.swift
  KioskProject/Presentation/Sources/Component/Button/OrderButton.swift
  KioskProject/Presentation/Sources/Component/Style/BorderStyle.swift
  KioskProject/Presentation/Sources/Component/TableViewCell/CartTableViewCell.swift
  KioskProject/Presentation/Sources/Model/CartItem.swift
  KioskProject/Presentation/Sources/Utils/AlertType.swift
  KioskProject/Presentation/Sources/Utils/CartSection.swift
  KioskProject/Presentation/Sources/Utils/Extension/Extension+Int.swift
  KioskProject/Presentation/Sources/Utils/Extension/Extension+UICollectionViewCell.swift
  KioskProject/Presentation/Sources/Utils/Extension/Extension+UIViewController.swift
  KioskProject/Presentation/Sources/Utils/Protocol/ResuableProtocol.swift
  KioskProject/Presentation/Sources/Utils/Protocol/ViewModel.swift
  KioskProject/Presentation/Sources/View/CartView.swift
  KioskProject/Presentation/Sources/View/Cell/CartTableViewCell.swift
  KioskProject/Presentation/Sources/View/Cell/ProductCollectionViewCell.swift
  KioskProject/Presentation/Sources/View/Cell/TotalAmountCell.swift
  KioskProject/Presentation/Sources/View/MainView.swift
  KioskProject/Presentation/Sources/View/OrderButtonView.swift
  KioskProject/Presentation/Sources/View/PaymentView.swift
  KioskProject/Presentation/Sources/View/TitleView.swift
  KioskProject/Presentation/Sources/ViewController/Delegate/CartCellDelegate.swift
  KioskProject/Presentation/Sources/ViewController/MainViewController.swift
  KioskProject/Presentation/Sources/ViewModel/MainViewModel.swift
Labels: documentation, enhancement

#26 Feature/#21 dark mode
  KioskProject/Presentation/Sources/Component/Button/OrderButton.swift
  KioskProject/Presentation/Sources/View/CartView.swift
  KioskProject/Presentation/Sources/View/CategoryView.swift
  KioskProject/Presentation/Sources/View/Cell/CartTableViewCell.swift
  KioskProject/Presentation/Sources/View/Cell/ProductCollectionViewCell.swift
  KioskProject/Presentation/Sources/View/Cell/TotalAmountCell.swift
  KioskProject/Presentation/Sources/View/MainView.swift
  KioskProject/Presentation/Sources/View/PaymentView.swift
  KioskProject/Presentation/Sources/View/TitleView.swift
Labels: enhancement

#27 refactor: HotLabel 추가 (#21)
  KioskProject/Presentation/Sources/Component/Button/OrderButton.swift
  KioskProject/Presentation/Sources/Component/Button/PaddingLabel.swift
  KioskProject/Presentation/Sources/View/Cell/ProductCollectionViewCell.swift
Labels: enhancement
